added ginln to create the links. modified gin to support GIN_PATH for repos.

diff --git a/gin b/gin
--- a/gin
+++ b/gin
@@ -3,88 +3,62 @@
   echo "Don't source this script! ${SELF}" >&2
   return
 }
-GIN_VERBOCITY=${GIN_VERBOCITY:-${VEROCITY:-${VERBOSE:-${V:-0}}}}
-{ ((GIN_VERBOCITY > 0)) || GIN_VERBOCITY=0; } >/dev/null 2>&1
-((GIN_VERBOCITY>=10)) && set -x
-GIN_VERBOSE_NAME=(SELFD SELF TYPE GINHUB GIN_NAME GIST)
-
-((GIN_VERBOCITY>1)) && {
-  echo "Environment unconfigured"
-  for n in ${GIN_VERBOSE_NAMES}; do
-    v=$(eval echo '$'${n})
-    echo "${n}=${v}"
-  done
-}
 
 GINHUB=${GINHUB:-'https://raw.github.com/gist'}
 GIN_NAME=${GIN_NAME:-gin}
-GIN_REPOS=(
-  ${HOME}/.${GIN_NAME}
-  ${PWD}/.${GIN_NAME}
-  ${HOME}/${GIN_NAME}
-  ${PWD}/${GIN_NAME}
-  ${SELFD}/../${GIN_NAME}
-)
 
 SELFD=$(cd $(dirname $0) >/dev/null 2>&1; pwd)
 SELF=$(basename $0)
 [ -x ${SELFD}/${SELF} ] || {
   echo "Whoa! ${SELF}" >&2
-  ((GIN_VERBOCITY>3)) && set
   exit ${LINENO}
 }
 TYPE=${SELF##*.}
 [ "${TYPE}" == "${SELF}" ] && TYPE=
-TYPE=".${TYPE}"
 SELF=${SELF%.*}
 TEST=${TEST:-false}
 
-for gist in ${GIN_REPOS[@]}; do
-  name=${gist}/${SELF}${TYPE}
-  ((GIN_VERBOCITY>2)) && {
-    echo "Testing ${name}"
-  }
-  [ -L ${name} ] && {
-    GIST=($(\ls -l ${name}))
-    GIST=${GIST[${#GIST}]}
-    ((GIN_VERBOCITY>1)) && {
-      echo "Found ${name} as ${GIST}"
-    }
+gin_temp=
+
+while :; do
+  [ -d ${PWD}/.${GIN_NAME} ] && gin_temp="${gin_temp:+${gin_temp}:}${PWD}"
+  [ ${PWD} == '/' ] && break
+  cd .. >/dev/null 2>&1
+done
+
+cd "${STARTD}"
+
+GIN_PATH="${gin_temp}${GIN_PATH:+:${GIN_PATH}}"
+
+GIST=
+
+OFS="${IFS}" IFS=':'
+for gin in ${GIN_PATH}; do
+  gin="${gin/[~]/${HOME}}"
+  gin_dest="${gin}/.${GIN_NAME}"
+  name="${gin_dest}/${SELF}"
+  [ -L "${name}" ] && {
+    GIST="${name}"
     break
   }
 done
+IFS="${OFS}"
+
 [ "${GIST}" ] || {
-  echo "${SELF} Not Found" >&2
+  echo "${SELF} not found" >&2
   exit ${LINENO}
 }
 
-((GIN_VERBOCITY>1)) && {
-  echo "Environment configured"
-  for n in ${GIN_VERBOSE_NAMES}; do
-    v=$(eval echo '$'${n})
-    echo "${n}=${v}"
-  done
+SCRIPT=$(\ls -l ${GIST} | awk '{print $NF}')
+TYPE=${SCRIPT##*.}
+[ "${TYPE}" == "${SCRIPT}" ] && {
+  # TODO: cache script locally and just execute it.
+  echo "${SCRIPT} unknown type" >&2
+  exit ${LINENO}
 }
+CURL="curl -ks ${GINHUB}/${SCRIPT}"
 
-[ "${TYPE}" ] || {
-  TYPE=${GIST##*.}
-  [ "${TYPE}" == "${GIST}" ] && {
-    echo "Can not execute a script without a type. ${SELF}" >&2
-    ((GIN_VERBOCITY>3)) && set
-    exit ${LINENO}
-  }
-  TYPE=".${TYPE}"
-}
-
-((GIN_VERBOCITY>0)) && echo ${SELF}.${TYPE} ${GIN_REPO}/${GIST}
-
-((GIN_VERBOCITY>4)) && {
-  CURL_VERBOSE='--verbose'
-}
-
-CURL="curl -ks ${CURL_VERBOSE} ${GINHUB}/${GIST}"
-
-[ '.sh' == ${TYPE} ] && {
+[ 'sh' == ${TYPE} ] && {
   ${TEST} && {
     echo "${CURL} | sh -s ${@}"
   } || {
@@ -93,7 +67,7 @@ CURL="curl -ks ${CURL_VERBOSE} ${GINHUB}/${GIST}"
   exit $?
 }
 
-[ '.py' == ${TYPE} ] && {
+[ 'py' == ${TYPE} ] && {
   ${TEST} && {
     echo "${CURL} | python"
   } || {
